name: GdUnit4 Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MikeSchulze/gdunit4-action@v1
        with:
          godot-version: '4.4.0'
          version: 'latest'
          godot-net: true
          warnings-as-errors: true
          paths: 'res://test'
